import os

print(os.getcwd())
os.makedirs('Папка\\Библиотека\\Журналы')
os.makedirs('Папка\\Журналы\\КомпьютерПресс')
os.makedirs('Папка\\Журналы\\Подводная лодка')
os.mkdir('Папка\\Книги')
os.makedirs('Папка\\Тетради\\Информатика\\Теория')
os.makedirs('Папка\\Тетради\\Математика')

t1 = open("Папка\\Библиотека\\Журналы\\journ1.txt", "w")
t1.close()
t2 = open("Папка\\Библиотека\\Журналы\\journ2.txt", "w")
t2.close()
t3 = open("Папка\\Журналы\\Подводная лодка\\lect1.txt", "w")
t3.close()
t4 = open("Папка\\Книги\\Верн.txt", "w")
t4.close()
t5 = open("Папка\\Книги\\Гарднер.txt", "w")
t5.close()
t6 = open("Папка\\Книги\\Свифт.txt", "w")
t6.close()
t7 = open("Папка\\Тетради\\Информатика\\Теория\\chapter1.txt", "w")
t7.close()
t8 = open("Папка\\Тетради\\Информатика\\Теория\\chapter2.txt", "w")
t8.close()
t9 = open("Папка\\опись.txt", "w")
t9.close()
t10 = open("Папка\\реестр.txt", "w")
t10.close()